name: Build and Deploy BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨1:00运行
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 缓存 Node.js 依赖
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # 使用缓存加速依赖安装
      - name: 缓存 Node.js 依赖
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: 安装依赖项
        run: |
          npm install

      # 如果worker.js文件已经存在，可跳过下载步骤
      - name: 下载 BPB worker.js
        run: |
          wget -O origin.js https://raw.githubusercontent.com/orangetect/BPB-Worker-Panel/refs/heads/main/src/worker.js

      # 提交更改
      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新最新的 BPB 面板'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
